//! The checked primitive manifest — the single source of truth for the 23 v0.x
//! primitives' canonical order, glyphs, arities, and stack effects.
//!
//! # One canonical table, many generated mirrors (issue #46)
//!
//! The 23 primitives used to be declared, by hand, in six-plus independent
//! places (parser `Prim`, Verus `SpecPrim`, interp `Prim`, `GLYPHS`, and the two
//! `conv` functions). PR #32 made *this* module the checked source of truth and
//! shipped `mtl-conformance` to *detect* drift after the fact. Issue #46 closes
//! the remaining gap — **prevention**: the mechanical mirrors are now *generated*
//! from the single canonical table [`for_each_primitive!`], so editing that table
//! propagates everywhere with zero hand-edits.
//!
//! [`for_each_primitive!`] is the one place the 23 rows live. It is an x-macro:
//! every mirror passes a small local callback macro that receives the rows and
//! expands them into that mirror's shape. Today it generates:
//!
//!   * [`PRIMITIVES`] / [`ALL_PRIMS`] / [`meta_of`] (this module);
//!   * [`crate::ast::Prim`] + [`crate::ast::GLYPHS`] (the parser/printer mirror);
//!   * `mtl_bench_validate::conv` and `mtl_host::conv` (the two `conv` opcode maps).
//!
//! What stays hand-written (design-review compromise, policed by comparison):
//!
//!   * the Verus `SpecPrim` (`crates/mtl-core/src/mtl_core.rs`) and every Verus
//!     proof root — the verified core must not gain a proc-macro/codegen
//!     dependency; `mtl-conformance`'s `verus_specprim_matches_manifest` backstops
//!     it;
//!   * the interp `Prim` (`crates/mtl-core/src/interp.rs`) — kept a genuinely
//!     independent mirror so the differential oracle has something to disagree
//!     with; policed by `interp_prim_names_match_manifest` + `interp_prim_exhaustive`.
//!
//! Two drift guards still live right here at compile time:
//!   * [`meta_of`] is generated as an exhaustive match over [`crate::ast::Prim`]
//!     with **no wildcard** — adding a `syntax::Prim` variant without a manifest
//!     row fails to compile here.
//!   * [`PRIMITIVES`] / [`ALL_PRIMS`] are fixed-size `[_; 23]` arrays — changing
//!     the row count without updating the `[_; 23]` shape fails to compile.

use crate::ast::Prim;

/// The **single canonical table** of the 23 v0.x primitives, in canonical order
/// (indices 0..=22). This x-macro is the one place the rows are written; every
/// mechanical mirror is generated by passing a callback macro that receives the
/// rows and expands them into that mirror's shape.
///
/// Each row is `(index, Name, glyph, arity, stack_effect)`:
///   * `index`  — canonical position, matching every mirror's enum order;
///   * `Name`   — the enum-variant identifier used verbatim in every mirror
///     (also what `format!("{:?}", prim)` produces);
///   * `glyph`  — the canonical single-character glyph;
///   * `arity`  — the minimum stack depth below which the interpreter faults
///     `Underflow` (pinned to real interpreter behaviour by
///     `mtl-conformance`'s `arity_matches_interp_underflow`);
///   * `stack_effect` — the spec stack-effect string (informational).
///
/// # Usage
///
/// Define a callback `macro_rules!` matching
/// `$(($idx:expr, $name:ident, $glyph:literal, $arity:literal, $eff:literal)),*`
/// and invoke `for_each_primitive!(that_callback)`. See [`meta_of`]'s generation
/// below, or `crate::ast` / `mtl-host` / `bench/validate` for real callers.
#[macro_export]
macro_rules! for_each_primitive {
    ($callback:ident) => {
        $callback! {
            //  idx  Name       glyph  arity  stack_effect
            (0,  Dup,     ':',  1, "( a -- a a )"),
            (1,  Drop,    '_',  1, "( a -- )"),
            (2,  Swap,    '~',  2, "( a b -- b a )"),
            (3,  Rot,     '@',  3, "( a b c -- b c a )"),
            (4,  Over,    '^',  2, "( a b -- a b a )"),
            (5,  Apply,   '!',  1, "( [q] -- ... )"),
            (6,  Cat,     ',',  2, "( [a] [b] -- [a b] )"),
            (7,  Cons,    ';',  2, "( v [q] -- [v q] )"),
            (8,  Dip,     '\'', 2, "( a [q] -- ... a )"),
            (9,  Add,     '+',  2, "( a b -- a+b )"),
            (10, Sub,     '-',  2, "( a b -- a-b )"),
            (11, Mul,     '*',  2, "( a b -- a*b )"),
            (12, Div,     '/',  2, "( a b -- a/b )"),
            (13, Mod,     '%',  2, "( a b -- a%b )"),
            (14, Eq,      '=',  2, "( a b -- c )"),
            (15, Lt,      '<',  2, "( a b -- c )"),
            (16, If,      '?',  3, "( c [t] [f] -- ... )"),
            (17, PrimRec, '&',  3, "( n [I] [C] -- r )"),
            (18, Times,   '.',  2, "( n [Q] -- ... )"),
            (19, LinRec,  '|',  4, "( [P] [T] [R1] [R2] -- ... )"),
            (20, Uncons,  '>',  1, "( [w ...] -- w [...] 1 ) | ( [] -- 0 )"),
            (21, Fold,    '(',  3, "( [seq] init [C] -- r )"),
            (22, Xor,     '$',  2, "( a b -- a^b )"),
        }
    };
}

/// Metadata for one MTL primitive.
pub struct PrimMeta {
    /// Canonical index, 0..=22, matching the position in every mirror's enum.
    pub index: u8,
    /// The enum-variant identifier used verbatim in every mirror (e.g. `"Dup"`).
    /// This is what `format!("{:?}", prim)` produces for each mirror's variant.
    pub name: &'static str,
    /// The canonical single-character glyph from `GLYPHS`.
    pub glyph: char,
    /// The minimum stack depth below which the interpreter faults `Underflow`
    /// for this primitive (derived from the `if stack.len() < K` guards in
    /// `mtl-core`'s `exec_prim`).
    pub arity: u8,
    /// The spec stack-effect string. Informational.
    pub stack_effect: &'static str,
}

/// Generate the manifest tables ([`PRIMITIVES`], [`ALL_PRIMS`]) and the
/// compile-time drift guard [`meta_of`] from the canonical rows.
macro_rules! define_manifest {
    ( $( ($idx:expr, $name:ident, $glyph:literal, $arity:literal, $eff:literal) ),* $(,)? ) => {
        /// The 23 v0.x primitives in canonical order, indices 0..=22.
        ///
        /// Generated from [`for_each_primitive!`]. The `[PrimMeta; 23]` shape is a
        /// compile-time guard: adding a row without widening the count fails here.
        pub const PRIMITIVES: [PrimMeta; 23] = [
            $(
                PrimMeta {
                    index: $idx,
                    name: stringify!($name),
                    glyph: $glyph,
                    arity: $arity,
                    stack_effect: $eff,
                }
            ),*
        ];

        /// Every [`crate::ast::Prim`] in canonical order, indices 0..=22.
        pub const ALL_PRIMS: [Prim; 23] = [ $( Prim::$name ),* ];

        /// Map a [`crate::ast::Prim`] to its manifest entry.
        ///
        /// Generated as an **exhaustive** match with no wildcard arm: it is the
        /// compile-time drift guard. Adding a `syntax::Prim` variant without a
        /// corresponding manifest row fails to compile here.
        pub const fn meta_of(p: Prim) -> &'static PrimMeta {
            match p {
                $( Prim::$name => &PRIMITIVES[$idx] ),*
            }
        }
    };
}

crate::for_each_primitive!(define_manifest);
