#!/usr/bin/env python3
"""report_tier2.py — token-measurement report for the Tier-2 dev corpus.

Sibling of report.py. Where report.py emits the FROZEN T_v0 baseline
(bench/BASELINE.md), this generator covers ONLY the `tier == "tier2"` tasks in
tasks.json (the `T_tier2-dev` set) and writes bench/BASELINE-TIER2.md. It never
touches BASELINE.md, so the frozen numbers stay intact.

Metric mirrors report.py exactly: STATIC program-source tokens under o200k_base
and cl100k_base, a single trailing newline stripped per file, ratio =
tokens(python-idiomatic) / tokens(mtl-v0.2) (higher = better for MTL), and a
token-SUM aggregate (same aggregation report.py uses for its headline).

    python3 bench/tokcount/report_tier2.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent          # bench/tokcount
_BENCH = _HERE.parent                            # bench
if str(_BENCH) not in sys.path:
    sys.path.insert(0, str(_BENCH))

from tokcount.tokcount import ENCODINGS, count, count_file, encoder_error  # noqa: E402

REPORT_DATE = "2026-07-12"
TIER2_SET = "T_tier2-dev"
# Frozen T_v0 v0.2 aggregate, reproduced from bench/BASELINE.md for contrast.
FROZEN_TV0_AGG = 3.72

O, CL = ENCODINGS  # "o200k_base", "cl100k_base"


def _tiktoken_version() -> str:
    try:
        import tiktoken
        return getattr(tiktoken, "__version__", "unknown")
    except ImportError:
        return "NOT INSTALLED"


def load_tier2_tasks() -> list[dict]:
    data = json.loads((_HERE / "tasks.json").read_text(encoding="utf-8"))
    tasks = data.get("tasks", []) if isinstance(data, dict) else data
    return [t for t in tasks if t.get("tier") == "tier2"]


def _cf(rel: str | None) -> dict[str, int | None]:
    if not rel:
        return {e: None for e in ENCODINGS}
    p = _BENCH / rel
    return count_file(p) if p.exists() else {e: None for e in ENCODINGS}


def _tk(text: str) -> tuple[int | None, int | None]:
    c = count(text)
    return c[O], c[CL]


def _fmt(v: int | None) -> str:
    return "—" if v is None else str(v)


def _ratio(idi: int | None, mtl: int | None) -> str:
    if idi is None or mtl in (None, 0):
        return "—"
    return f"{idi / mtl:.2f}x"


def _verdict(task: dict) -> str:
    if not task.get("expressible", False):
        return "inexpressible"
    # "solved-but-ugly": the deep-stack-juggling accumulator solutions.
    ugly = {"max_list", "min_list", "reverse_list", "contains", "count_occurrences"}
    return "solved-but-ugly" if task["id"] in ugly else "solved"


def build_report() -> str:
    tasks = load_tier2_tasks()
    tk_version = _tiktoken_version()

    counts = {}
    for t in tasks:
        f = t.get("files", {})
        counts[t["id"]] = {
            "mtl": _cf(f.get("mtl_v0_2")),
            "idi": _cf(f.get("python_idiomatic")),
            "min": _cf(f.get("python_minified")),
        }

    solvable = [t for t in tasks if t.get("expressible")]
    walls = [t for t in tasks if not t.get("expressible")]

    L: list[str] = []
    L.append("# MTL Token Baseline — Tier-2 dev corpus (`" + TIER2_SET + "`)")
    L.append("")
    L.append("<!-- GENERATED by bench/tokcount/report_tier2.py — do not edit by hand. -->")
    L.append("")
    L.append(f"- Date: {REPORT_DATE}")
    L.append(f"- Corpus set: {TIER2_SET} (tier2, dev split) — anti-gaming: added AFTER "
             "the frozen T_v0 gate, kept in a separate set/file.")
    L.append(f"- tiktoken version: {tk_version}")
    L.append(f"- Encodings: {', '.join(ENCODINGS)} (OpenAI tiktoken, public proxy).")
    L.append("- Metric: STATIC program-source tokens. Ratio = tokens(python-idiomatic) / "
             "tokens(mtl-v0.2), same encoding; higher = better for MTL.")
    L.append("- Counting policy: a single trailing newline stripped per file, uniform "
             "across variants (identical to report.py / BASELINE.md).")
    L.append("- This file is separate from the frozen bench/BASELINE.md; those T_v0 "
             "numbers are untouched.")
    L.append("")

    unavailable = [(e, encoder_error(e)) for e in ENCODINGS if encoder_error(e)]
    L.append("## Tokenizer availability")
    L.append("")
    if unavailable:
        for e, err in unavailable:
            L.append(f"- **TOKENIZER UNAVAILABLE: {e} — {err}**")
    else:
        L.append("- All encoders loaded and encoded successfully.")
    L.append("")

    # Per-task table.
    L.append("## Per-task token counts — 13 tier-2 tasks")
    L.append("")
    L.append("MTL column is UNAVAIL (`—`) for the 3 inexpressible walls (no MTL solution "
             "exists). Ratio compares idiomatic Python to MTL v0.2.")
    L.append("")
    L.append("| Task | Category | mtl-v0.2 (o200k) | py-idiomatic (o200k) | ratio (o200k) "
             "| mtl-v0.2 (cl100k) | py-idiomatic (cl100k) | ratio (cl100k) | expressibility |")
    L.append("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | :---: |")
    for t in tasks:
        c = counts[t["id"]]
        m, idi = c["mtl"], c["idi"]
        L.append(
            f"| {t['id']} | {t.get('category','')} | {_fmt(m[O])} | {_fmt(idi[O])} | "
            f"{_ratio(idi[O], m[O])} | {_fmt(m[CL])} | {_fmt(idi[CL])} | "
            f"{_ratio(idi[CL], m[CL])} | {_verdict(t)} |"
        )
    L.append("")

    # Aggregate over the 10 solvable tasks (token-sum ratio, like report.py).
    def agg(variant: str, enc: str) -> int:
        return sum(counts[t["id"]][variant][enc] for t in solvable)

    L.append("## Tier-2 aggregate MTL reduction (10 solvable tasks)")
    L.append("")
    L.append("Aggregate ratio = sum(idiomatic-python tokens) / sum(mtl-v0.2 tokens) over "
             "the 10 expressible tier-2 tasks, per encoding (same token-sum aggregation "
             "as report.py's headline). Walls are excluded (no MTL denominator).")
    L.append("")
    L.append("| Encoding | idiomatic-py total | mtl-v0.2 total | aggregate ratio | vs frozen T_v0 (3.72x) |")
    L.append("| --- | ---: | ---: | ---: | :---: |")
    tier2_ratios = {}
    for enc in ENCODINGS:
        it, mt = agg("idi", enc), agg("mtl", enc)
        r = it / mt
        tier2_ratios[enc] = r
        L.append(f"| {enc} | {it} | {mt} | {r:.2f}x | {r - FROZEN_TV0_AGG:+.2f}x (lower) |")
    L.append("")
    L.append(f"**Honest finding:** the tier-2 aggregate ({tier2_ratios[O]:.2f}x o200k, "
             f"{tier2_ratios[CL]:.2f}x cl100k) is well BELOW the frozen T_v0 aggregate of "
             f"{FROZEN_TV0_AGG:.2f}x. MTL's compression edge is on recursion / "
             "control-heavy code (the T_v0 recursion tasks), NOT on simple iteration and "
             "list traversal, where a Python `for` loop is already terse and MTL pays a "
             "large stack-juggling tax. Reporting this gap is the point of the tier-2 "
             "probe.")
    L.append("")

    # Expressibility table.
    L.append("## Expressibility verdict")
    L.append("")
    n_solved = sum(1 for t in solvable if _verdict(t) == "solved")
    n_ugly = sum(1 for t in solvable if _verdict(t) == "solved-but-ugly")
    L.append(f"**{len(solvable)}/13 solved** ({n_solved} clean, {n_ugly} solved-but-ugly) "
             f"· **{len(walls)}/13 inexpressible**. Every solvable solution is "
             "interpreter-validated (bench/validate/tests/tier2.rs, all vectors Halt).")
    L.append("")
    L.append("| Task | Verdict | Note |")
    L.append("| --- | :---: | --- |")
    notes = {
        "sum_list": "clean linrec fold (`[>0=][0][][+]|`)",
        "length_list": "clean linrec fold",
        "product_list": "clean linrec fold",
        "climbing_stairs": "clean Times/iterative pair (8 tok — the tightest win)",
        "palindrome_number": "clean linrec digit-reverse",
        "max_list": "non-destructive null test + re-uncons + dip, ~39 glyphs",
        "min_list": "same shape as max_list",
        "reverse_list": "cons-accumulator + dip, 31 glyphs; output is a quotation",
        "contains": "threads carried scalar x past the accumulator each step (rot+over+swap)",
        "count_occurrences": "same juggling as contains",
        "single_number": "no bitwise XOR primitive",
        "two_sum": "no positional index / enumerate / map",
        "binary_search": "cons-list has no O(1) random access",
    }
    for t in tasks:
        L.append(f"| {t['id']} | {_verdict(t)} | {notes.get(t['id'],'')} |")
    L.append("")

    # v0.3 candidate evidence — computed token taxes.
    null_idiom = "[>[;0][[]1]?]"
    null_o, null_cl = _tk(null_idiom)
    accum_tasks = ["max_list", "min_list", "reverse_list", "contains", "count_occurrences"]
    accum_o = sum(counts[t]["mtl"][O] for t in accum_tasks)
    accum_cl = sum(counts[t]["mtl"][CL] for t in accum_tasks)
    fold_target = 8 * len(accum_tasks)  # hypothetical ~8-tok fold each

    L.append("## v0.3 candidate evidence — missing primitives ranked")
    L.append("")
    L.append("Ranked by (a) tasks blocked outright and (b) token-tax paid across the "
             "corpus for hand-rolling the missing capability. Token figures are measured "
             "(o200k_base / cl100k_base).")
    L.append("")
    L.append("### 1. Random-access / indexed sequence (`index`/`nth`, enumerate)")
    L.append(f"- **Blocks 2 tasks** (two_sum, binary_search) — the biggest STRUCTURAL "
             "gap. A quotation is a cons-list with only sequential `>` uncons; it cannot "
             "index in O(1) nor recover element positions.")
    L.append("- No token-tax workaround exists — these tasks are simply absent from the "
             "MTL column.")
    L.append("")
    L.append("### 2. Bitwise ops (xor / and / or / shift)")
    L.append("- **Blocks 1 task** (single_number) but a whole PROBLEM CLASS. Glyphs "
             "`&`,`^`,`|` are already taken (PrimRec, Over, LinRec); there is no bit "
             "access on `Int`.")
    L.append("- With `xor`, single_number collapses to a ~5-token fold `[0][xor]|`, "
             "matching the arithmetic folds.")
    L.append("")
    L.append("### 3. map / fold / filter combinator (or `pickN`/`dip-n` closure over a carried value)")
    L.append(f"- **Blocks 0 tasks** (all solved) but is the biggest TOKEN + WRITABILITY "
             f"win. The 5 accumulator solutions (max/min/reverse/contains/count) cost "
             f"**{accum_o} / {accum_cl} tokens** combined. A fold/`pickN` combinator that "
             f"carried the accumulator (and scalar) for the author would collapse each "
             f"toward ~8 tokens (~{fold_target} total), a **token tax of ~{accum_o - fold_target} "
             f"/ ~{accum_cl - fold_target} tokens** paid purely for hand-rolled stack juggling.")
    L.append("")
    L.append("### 4. `null?` / `empty?` / `len` primitive")
    L.append(f"- **Blocks 0 tasks** but every non-trivial list task re-implements the "
             f"non-destructive null test `{null_idiom}` (**{null_o} / {null_cl} tokens** "
             f"each). It appears in 5 tier-2 solutions (max, min, reverse, contains, "
             f"count) = **~{null_o * 5} / {null_cl * 5} tokens** spent re-deriving "
             f"`empty?` across the corpus. A primitive `empty?` erases that tax and "
             "removes the rebuild-then-re-uncons footgun (see writability note).")
    L.append("")
    L.append("### 5. Comparison variants (`>`, `<=`) + boolean and/or/not")
    L.append("- **Blocks 0 tasks**; minor per-task tax. `>` is taken by uncons, so "
             "greater-than is done by operand swap, and OR is synthesized as `+0~<` "
             "(4 tokens, valid only because flags are non-negative). A real `or`/`gt` "
             "would shave a few tokens per predicate.")
    L.append("")

    # LLM-writability observations.
    L.append("## LLM-writability observations")
    L.append("")
    L.append("These tasks were authored against a live interpreter; two recurring "
             "failure modes make the case that v0.2 MTL is hard to write correctly "
             "blind:")
    L.append("")
    L.append("1. **The max/min/reverse null-test bug.** The non-destructive null test "
             f"`{null_idiom}` REBUILDS the list, so the recursive branch must re-uncons "
             "with `>_` (not `_`) before touching the head. The first drafts used a bare "
             "`_`; **single-element inputs FALSE-PASSED** (they never enter the recursive "
             "branch), masking an `Underflow` fault that only appears on multi-element "
             "inputs. A blind author would ship the single-element-passing version.")
    L.append("2. **Threading a scalar past the accumulator.** contains / count carry a "
             "scalar `x` beneath a running accumulator; every loop iteration needs "
             "rot + over + swap to bring `x` adjacent to the current head and then "
             "restore the loop shape. The state layout (`found x list`) had to be chosen "
             "so `x` sits at a fixed reachable depth — reasoning no token-count metric "
             "rewards, and easy to get wrong.")
    L.append("")
    L.append("**Conclusion:** v0.2 MTL is hard to write correctly WITHOUT an interpreter "
             "in the loop. Static token compression (this report) is necessary but not "
             "sufficient evidence; the north-star metric needs an agent-writability trial "
             "(success rate x correction attempts), which these observations motivate.")
    L.append("")

    return "\n".join(L)


def main() -> int:
    report = build_report()
    print(report)
    out = _BENCH / "BASELINE-TIER2.md"
    out.write_text(report + "\n", encoding="utf-8")
    print(f"\n[report_tier2.py] wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
