#!/usr/bin/env python3
"""report.py — walk the MTL benchmark corpus and emit a token-measurement report.

Stage 1 of the MTL north-star metric: static program-source token counts under
the o200k_base and cl100k_base tiktoken encodings. The headline is the MTL
token-reduction ratio versus idiomatic Python (higher = better for MTL).

Runs from anywhere: paths resolve relative to this script, not the cwd.

    python3 bench/tokcount/report.py

Writes the markdown report to stdout AND to bench/BASELINE.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Make `import tokcount` work regardless of cwd by putting bench/ on sys.path.
_HERE = Path(__file__).resolve().parent          # bench/tokcount
_BENCH = _HERE.parent                            # bench
_REPO = _BENCH.parent                            # repo root
if str(_BENCH) not in sys.path:
    sys.path.insert(0, str(_BENCH))

from tokcount.tokcount import ENCODINGS, count_file, encoder_error  # noqa: E402

# Hardcoded per task spec — do not call datetime.now (keep report reproducible).
REPORT_DATE = "2026-07-11"
CORPUS_VERSION = "T_v0"

# Variant key -> (corpus subdir name, display label, tasks.json files-key)
VARIANTS = [
    ("mtl", "mtl", "mtl"),
    ("python-idiomatic", "python-idiomatic", "python_idiomatic"),
    ("python-minified", "python-minified", "python_minified"),
]
IDIOMATIC = "python-idiomatic"  # ratio baseline


def _tiktoken_version() -> str:
    try:
        import tiktoken
        return getattr(tiktoken, "__version__", "unknown")
    except ImportError:
        return "NOT INSTALLED"


def load_tasks() -> list[dict]:
    """Load tasks.json; fall back to a directory scan of corpus/."""
    manifest = _HERE / "tasks.json"
    if manifest.exists():
        data = json.loads(manifest.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return data.get("tasks", [])
        return data
    # Fallback: scan corpus/ directories.
    tasks = []
    corpus = _BENCH / "corpus"
    for d in sorted(p for p in corpus.iterdir() if p.is_dir()):
        tasks.append({
            "id": d.name,
            "category": "unknown",
            "split": "dev",
            "description": "",
            "files": {
                "mtl": f"corpus/{d.name}/mtl/solution.mtl",
                "python_idiomatic": f"corpus/{d.name}/python-idiomatic/solution.py",
                "python_minified": f"corpus/{d.name}/python-minified/solution.py",
            },
        })
    return tasks


def _fmt_tok(v: int | None) -> str:
    return "UNAVAIL" if v is None else str(v)


def _fmt_ratio(idi: int | None, variant: int | None) -> str:
    if idi is None or variant is None:
        return "n/a"
    if variant == 0:
        return "inf"
    return f"{idi / variant:.2f}x"


def build_report() -> str:
    tasks = load_tasks()
    tk_version = _tiktoken_version()

    # counts[task_id][variant_key][encoding] = int | None
    counts: dict[str, dict[str, dict[str, int | None]]] = {}
    for task in tasks:
        tid = task["id"]
        counts[tid] = {}
        for variant_key, _label, files_key in VARIANTS:
            rel = task.get("files", {}).get(files_key)
            path = _BENCH / rel if rel else None
            if path and path.exists():
                counts[tid][variant_key] = count_file(path)
            else:
                counts[tid][variant_key] = {enc: None for enc in ENCODINGS}

    lines: list[str] = []
    lines.append("# MTL Token Baseline — " + CORPUS_VERSION)
    lines.append("")
    lines.append("<!-- GENERATED by bench/tokcount/report.py — do not edit by hand. -->")
    lines.append("")
    lines.append(f"- Date: {REPORT_DATE}")
    lines.append(f"- Corpus version: {CORPUS_VERSION}")
    lines.append(f"- tiktoken version: {tk_version}")
    lines.append(f"- Encodings: {', '.join(ENCODINGS)} (OpenAI tiktoken, public proxy for LLM tokenization)")
    lines.append("- Metric: STATIC program-source tokens (stage 1). Ratio column = "
                 "tokens(python-idiomatic) / tokens(variant), same encoding; higher = better for MTL.")
    lines.append("- Counting policy: a single trailing newline is stripped from every file "
                 "before counting, applied uniformly to all variants.")
    lines.append("")

    # Encoder availability banner.
    unavailable = []
    for enc in ENCODINGS:
        err = encoder_error(enc)
        if err:
            unavailable.append((enc, err))
    if unavailable:
        lines.append("## Tokenizer availability")
        lines.append("")
        for enc, err in unavailable:
            lines.append(f"- **TOKENIZER UNAVAILABLE: {enc} — {err}**")
        lines.append("")
    else:
        lines.append("## Tokenizer availability")
        lines.append("")
        lines.append("- All encoders loaded and encoded successfully.")
        lines.append("")

    # Per-task table.
    lines.append("## Per-task token counts")
    lines.append("")
    header = ("| Task | Category | Variant | o200k_base tok | cl100k_base tok "
              "| ratio-vs-idiomatic-py (o200k) | ratio (cl100k) |")
    sep = "| --- | --- | --- | ---: | ---: | ---: | ---: |"
    lines.append(header)
    lines.append(sep)
    for task in tasks:
        tid = task["id"]
        cat = task.get("category", "")
        idi = counts[tid][IDIOMATIC]
        for variant_key, label, _fk in VARIANTS:
            c = counts[tid][variant_key]
            o = c[ENCODINGS[0]]
            cl = c[ENCODINGS[1]]
            r_o = _fmt_ratio(idi[ENCODINGS[0]], o)
            r_cl = _fmt_ratio(idi[ENCODINGS[1]], cl)
            lines.append(
                f"| {tid} | {cat} | {label} | {_fmt_tok(o)} | {_fmt_tok(cl)} | {r_o} | {r_cl} |"
            )
    lines.append("")

    # Summary / totals.
    totals: dict[str, dict[str, int | None]] = {}
    any_missing: dict[str, bool] = {}
    for variant_key, _label, _fk in VARIANTS:
        totals[variant_key] = {}
        for enc in ENCODINGS:
            vals = [counts[t["id"]][variant_key][enc] for t in tasks]
            if any(v is None for v in vals):
                totals[variant_key][enc] = None
                any_missing[(variant_key, enc)] = True
            else:
                totals[variant_key][enc] = sum(vals)  # type: ignore[arg-type]

    lines.append("## Corpus totals")
    lines.append("")
    lines.append("| Variant | o200k_base total | cl100k_base total |")
    lines.append("| --- | ---: | ---: |")
    for variant_key, label, _fk in VARIANTS:
        o = totals[variant_key][ENCODINGS[0]]
        cl = totals[variant_key][ENCODINGS[1]]
        lines.append(f"| {label} | {_fmt_tok(o)} | {_fmt_tok(cl)} |")
    lines.append("")

    # Aggregate headline ratio = sum(idiomatic py) / sum(mtl), per encoding.
    lines.append("## Aggregate MTL reduction (headline)")
    lines.append("")
    lines.append("Aggregate ratio = sum(idiomatic-python tokens) / sum(mtl tokens), per encoding.")
    lines.append("")
    lines.append("| Encoding | idiomatic-py total | mtl total | aggregate ratio | >=3x gate |")
    lines.append("| --- | ---: | ---: | ---: | :---: |")
    gate_status: dict[str, str] = {}
    for enc in ENCODINGS:
        idi_total = totals[IDIOMATIC][enc]
        mtl_total = totals["mtl"][enc]
        if idi_total is None or mtl_total is None or mtl_total == 0:
            ratio_str = "n/a"
            gate = "n/a"
        else:
            ratio = idi_total / mtl_total
            ratio_str = f"{ratio:.2f}x"
            gate = "MET" if ratio >= 3.0 else "NOT MET"
        gate_status[enc] = gate
        lines.append(f"| {enc} | {_fmt_tok(idi_total)} | {_fmt_tok(mtl_total)} | {ratio_str} | {gate} |")
    lines.append("")

    lines.append("### Gate verdict")
    lines.append("")
    for enc in ENCODINGS:
        lines.append(f"- **{enc}: >=3x reduction {gate_status[enc]}** on this seed corpus.")
    lines.append("")
    lines.append("### Caveats")
    lines.append("")
    lines.append("- The MTL solutions are now **parse-and-execute validated**: each is run "
                 "against the merged `mtl-syntax` parser and `mtl-core` interpreter by "
                 "`bench/validate/tests/corpus.rs`, which checks every task against multiple "
                 "input/output vectors. Token counts are exact; correctness is executed, not "
                 "merely structural.")
    lines.append("- The two **recursion** tasks (factorial, gcd) were originally structural "
                 "sketches that **faulted (TypeMismatch)** on execution; they have been "
                 "corrected to interpreter-verified programs. Their token counts rose "
                 "accordingly (factorial 12->19, gcd 12->15).")
    lines.append("- This is still **stage 1** (static program tokens) of the full metric. The "
                 "real north-star is E[total inference tokens x attempts to correct] under a "
                 "warm/cold agent protocol (spec section 10); stages 2+ add agent success rate.")
    lines.append("- Corpus is versioned `" + CORPUS_VERSION + "` and populated only on the "
                 "`dev` split; `train` and `sealed-eval` are reserved-empty in v0.")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    report = build_report()
    print(report)
    out = _BENCH / "BASELINE.md"
    out.write_text(report + "\n", encoding="utf-8")
    print(f"\n[report.py] wrote {out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
